[package]
name = "flaca"
version = "1.3.4"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "Brute-force, lossless JPEG and PNG compression."
publish = false

[package.metadata.deb]
maintainer = "Josh Stoik <hello@blobfolio.com>"
copyright = "2020, Blobfolio, LLC <hello@blobfolio.com>"
license-file = ["../LICENSE", "0"]
extended-description = """\n\
Flaca is a CLI app written in Rust to aid the complex task of squeezing every last drop of space out of JPEG and PNG images — without sacrificing quality.\n\
.\n\
Under the hood, it uses MozJPEG for lossless JPEG (re)compression, and Oxipng/Zopflipng for lossless PNG (re)compression."""
revision = "1"
depends = "$auto, libjpeg-turbo-progs, libturbojpeg1 | libjpeg62-turbo | libjpeg-turbo8, zopflipng"
section = "utility"
assets = [
    ["../target/x86_64-unknown-linux-gnu/release/flaca", "usr/bin/", "755"],
    ["../skel/completions/flaca.bash", "etc/bash_completion.d/", "644"],
    ["../skel/man/flaca.1.gz", "usr/share/man/man1/", "644"],
]

[dependencies.flaca_core]
path = "../flaca_core"

[dependencies.fyi_menu]
git = "https://github.com/Blobfolio/fyi.git"
branch = "master"

[dependencies.fyi_msg]
git = "https://github.com/Blobfolio/fyi.git"
branch = "master"

[dependencies.fyi_progress]
git = "https://github.com/Blobfolio/fyi.git"
branch = "master"

[dependencies.fyi_witcher]
git = "https://github.com/Blobfolio/fyi.git"
branch = "master"

[features]
default = []
man = []
