[package]
name = "flaca"
version = "1.1.3"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "Brute-force, lossless JPEG and PNG compression."
build = "build.rs"
publish = false

[build-dependencies]
clap = "2.33.*"

[dependencies]
flaca_core = { path = "../flaca_core" }
rayon = "1.3.*"
regex = "1.3.6"

[dependencies.clap]
version = "2.33.*"
default-features = false
features = [ "color", "suggestions", "vec_map", "wrap_help" ]

[dependencies.fyi_core]
git = "https://github.com/Blobfolio/fyi.git"
branch = "master"
default-features = false
features = [ "progress", "witcher" ]
