[package]
name = "flaca"
version = "1.0.0"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "Losslessly compress la mierda out of JPEG and PNG images."

[dependencies]
flaca_core = { path = "../flaca_core" }
ansi-escapes = "0.1.*"
ansi_term = "0.12.*"
crossbeam-channel = "0.4.*"
rayon = "1.2.*"
strip-ansi-escapes = "0.1.*"
term_size = "0.3.*"

[dependencies.clap]
version = "2.33.*"
default-features = false
features = [ "color", "suggestions", "vec_map", "wrap_help" ]
