[package]
name = "flaca"
version = "1.2.3"
license = "WTFPL"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "Brute-force, lossless JPEG and PNG compression."
publish = false

[package.metadata.deb]
maintainer = "Josh Stoik <hello@blobfolio.com>"
copyright = "2020, Blobfolio, LLC <hello@blobfolio.com>"
license-file = ["../LICENSE", "0"]
extended-description = """\n\
Flaca is a CLI frontend written in Rust to aid the complex task of squeezing every last drop of space out of JPEG and PNG images — without sacrificing quality.\n\
.\n\
Flaca uses MozJPEG and Jpegoptim for lossless JPEG (re)compression and PNGOUT, Oxipng, and Zopflipng for lossless PNG (re)compression.\n\
.\n\
The image compression binaries are not bundled with this package and must be installed separately."""
revision = "1"
depends = "$auto, libjpeg-turbo-progs, libturbojpeg1 | libjpeg62-turbo | libjpeg-turbo8, jpegoptim, oxipng, pngout, mozjpeg, zopflipng"
section = "utility"
assets = [
    ["../target/x86_64-unknown-linux-gnu/release/flaca", "usr/bin/", "755"],
    ["./misc/flaca.bash", "etc/bash_completion.d/", "644"],
    ["./misc/flaca.1.gz", "usr/share/man/man1/", "644"],
]

[dependencies]
jwalk = "*"

[dependencies.flaca_core]
path = "../flaca_core"

[dependencies.fyi_menu]
git = "https://github.com/Blobfolio/fyi.git"
branch = "master"

[dependencies.fyi_witcher]
git = "https://github.com/Blobfolio/fyi.git"
branch = "master"

[features]
default = []
man = []
