[package]
name = "flaca_core"
version = "1.1.0"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "Brute-force, lossless JPEG and PNG compression."
publish = false

[dependencies]
imghdr = "0.7.*"
lazy_static = "1.4.*"

[dependencies.fyi_core]
git = "https://github.com/Blobfolio/fyi.git"
default-features = false
features = [ "progress", "witcher" ]
