[package]
name = "flaca_core"
version = "1.2.3"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "Brute-force, lossless JPEG and PNG compression."
publish = false

[dependencies]
imghdr = "0.7.*"
lazy_static = "1.4.*"

[dependencies.oxipng]
version = "3.0.*"
default-features = false
features = [ "parallel" ]

[dependencies.fyi_msg]
git = "https://github.com/Blobfolio/fyi.git"
branch = "master"

[dependencies.fyi_witcher]
git = "https://github.com/Blobfolio/fyi.git"
branch = "master"
default-features = false
features = [ "witch_io" ]
