[package]
name = "flaca_core"
version = "1.3.9"
authors = ["Josh Stoik <josh@blobfolio.com>"]
edition = "2018"
description = "Brute-force, lossless JPEG and PNG compression."
publish = false

[dependencies]
imghdr = "0.7.*"
lazy_static = "1.4.*"
libc = "*"
tempfile = "3.1.*"
tempfile-fast = "0.3.*"

[dependencies.mozjpeg-sys]
path = "../mozjpeg_sys"
default-features = false
features = [ "turbojpeg_api", "nasm_simd" ]

[dependencies.oxipng]
version = "3.0.*"
default-features = false

[dependencies.fyi_msg]
git = "https://github.com/Blobfolio/fyi.git"
branch = "master"

[dependencies.fyi_witcher]
git = "https://github.com/Blobfolio/fyi.git"
branch = "master"
