.TH "FLACA" "1" "November 2021" "Flaca v1.7.8" "User Commands"
.SH NAME
Flaca \- Manual page for flaca v1.7.8.
.SH DESCRIPTION
Brute\-force, lossless JPEG and PNG compression.
.SS USAGE:
.TP
flaca [FLAGS] [OPTIONS] <PATH(s)…>
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information.
.TP
\fB\-p\fR, \fB\-\-progress\fR
Show progress bar while working.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print program version.
.SS OPTIONS:
.TP
\fB\-l\fR, \fB\-\-list\fR <FILE>
Read file paths from this text file.
.SS <PATH(S)…>:
.TP
Any number of files and directories to crawl and crunch.
.SS OPTIMIZERS:
.TP
\fBMozJPEG\fR
<https://github.com/mozilla/mozjpeg>
.TP
\fBOxipng\fR
<https://github.com/shssoichiro/oxipng>
.TP
\fBZopflipng\fR
<https://github.com/google/zopfli>
