.TH "FLACA" "1" "April 2022" "Flaca v1.9.1" "User Commands"
.SH NAME
Flaca \- Manual page for flaca v1.9.1.
.SH DESCRIPTION
Brute\-force, lossless JPEG and PNG compression.
.SS USAGE:
.TP
flaca [FLAGS] [OPTIONS] <PATH(s)…>
.SS FLAGS:
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help information and exit.
.TP
\fB\-\-no\-jpeg\fR
Skip JPEG images.
.TP
\fB\-\-no\-png\fR
Skip PNG images.
.TP
\fB\-p\fR, \fB\-\-progress\fR
Show progress bar while minifying.
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version information and exit.
.SS OPTIONS:
.TP
\fB\-l\fR, \fB\-\-list\fR <FILE>
Read (absolute) image and/or directory paths from this text file, one entry per line.
.SS <PATH(S)…>:
.TP
One or more image and/or directory paths to losslessly compress.
.SS OPTIMIZERS:
.TP
\fBMozJPEG\fR
<https://github.com/mozilla/mozjpeg>
.TP
\fBOxipng\fR
<https://github.com/shssoichiro/oxipng>
.TP
\fBZopflipng\fR
<https://github.com/google/zopfli>
